server:
  port: 8088
spring:
  datasource:
    name: test
    url: jdbc:mysql://47.104.24.168:3306/zc?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  security:
    user:
      name: admin
      password: 123456